language: node_js

node_js:
  - '11'

env:
  - CXX=g++-4.8

addons:
  apt:

    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8

before_install:
  - npm install -g npm@latest

after_install:
  - npm config set tag-version-prefix "" --global
  - npm config set tag-version-prefix ""

before_script:
  - npm version `git describe --tags` --no-git-tag
  - cat package.json | grep version

script:
  - gulp

before_deploy:
  - rm -rf src/test

deploy:

  - provider: npm
    email: peterc@aetheric.co.nz
    skip_cleanup: true
    api_key:
      secure: "\
        iS+K/ACit/g80L88kOEnPE4fpm72ZWVahLB7UKrxpNRBlETC3blIu8bXTEqpHXNA0xa3WhIPt/0hnGVL\
        GLWYT8jpc+t8SEu2GCozDKpzSvZ8Ni2odwNJpb/ki8sg2KX5dJAWX3TfRKv8g0Lf4HH+JAG5uaq6yDxl\
        7aiilhFYzMDHjn+WRyzFMc9kzcEp+bxBA/Tt/8ufNIb+txRr31N9yVJ2fAeGdN+vASBHHL8YX+u4J7I8\
        U7kJ+7nsGUibcRb70XNtM3GWSPAfPDZRhw9egV4sF84RH7VXfpeZBwKGoahBHtl33R2qdVZpwLu8Fmst\
        mYF0hnYT/0XVeVWfmw0K94JOpjNBhOoDdIlDgInhop9+OPdj0RgnpYxqrRiyYmkdrGIioEgll1pGNAQX\
        rN4oCsADKCDXLDIlGMS9ubuPDsO+33+CXnS3EjXxux6Vlgq5tdVoyQvs4g2I1UhUzAT14MAGeDAZHSRi\
        2KVNRFtKES6x1K7jZz00nGZ7yaAmF4i4vxTP2C13cgF/gKDv0TrNqRX2ODtzvBnTaBXvjQyPGJRNGkgu\
        asJSX81Rn1eUn7D+paRe9klJBNzyjHddyVZiEyyn6UMbZFl0r2Eba78YznNHSOxEyvtP8recoOCF8lvC\
        k1pP+FEhJ9vgRk2xbtvCe1hmcgxXKGBI6+kVVgy+bUg=\
      "
    on:
      repo: aetheric/http-constants
      all_branches: true

  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "\
        YPsMxpn79b3iubeKq52ZRmgnE1eNUEd/f9OfoSX3gMThm1DhTwD+Ok7ySpnHVjpEYCLURvA3Au1tDjAd\
        ad+A12Py+sME2+bQVqNA1Z9Ku3yzks+3BETnOFrcfW/dtlmDA/dLwFp6crswnC3o5ANxmpxaj0ECmJ0p\
        U+642E+KfNLg4aG4DMp5TmOU9jfYgZ4ZmtLHT4bUipq8sQF1Th36JSesVp8B0VImszTojv3u80JRzw7Q\
        NMuHaGHns6jBu8W9qdEYTSLNnwS7tBV+ejUYAHCvEKQumnEFivL/lpeL4XqPZ7Asbu09R+jmph9RbJ5v\
        PfrmDP854Q5fxcVORKT5sBLekRJIEkpUivLDDmfGtFrMhzrHEEnFH9wykYLu0xXnN01TALtuML8LcQt8\
        7WYHoBr0MgMnjd+eENePIjTFjDeO6JNn+JSsEN6xRUwF8TD/YleD4QXqbzIep9har7fLfFkIjpHQcT2p\
        f/aYAbu33XU+kuLaVZ7XdMj0kW5kEysMcpXaHjsjZ+WS3hHi/WvkMaPlI7xadssJsx6U3/j1gh9XGo4m\
        Sb9lMhlvKgdL3YY3zz01z5kjRSfgn/fFYB6UAfHNyNSsQhaqpYYwzuOTLSFKmN9W74gcOpaK1472/3Wz\
        nZiFXdxdVn9iQswsmWi7IsnhdmVcmll9hucAaIz16bU=\
      "
    file:
      - target/dist/consts.js
      - target/dist/consts.min.js
    on:
      repo: aetheric/http-constants
      tags: true
