language: node_js

node_js:
  - '11'

env:
  - CXX=g++-4.8

addons:
  apt:

    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-4.8

before_install:
  - npm install -g npm@latest

after_install:
  - npm config set tag-version-prefix "" --global
  - npm config set tag-version-prefix ""

before_script:
  - npm version `git describe --tags` --no-git-tag
  - cat package.json | grep version

script:
  - gulp

before_deploy:
  - rm -rf src/test

deploy:

  - provider: npm
    email: peterc@aetheric.co.nz
    skip_cleanup: true
    api_key:
      secure: "\
        GLpS6fcQe6hT5of2abCwH2tjDW89hPwcJogQ4RzLvbcEseBKJ6YyLjVLQn4Kyq3h5zm02lSpBfu8Vrxv\
        owa4ZConzoRV88wHllRaGMhSp5xV0srG30tBgATiVwsOUfnH5gXk6wVGuSrcb+CENLzE9UGfIC/VyfJI\
        lAAg/t8KCHLXgBR+Lj7dlEgg6IKehhDuerFRNH2vzFPUHAFqVPJ4p98rfA81jFMTC8l4Bk0CbWYYJfg2\
        z8OP2yTjnwDq5xHp2t97dxJvJKddqmgDCEnljG+djU9ehWQTadtGUROKIwoPo9VCUs37rAx74op1+RZA\
        NkW6EmI4XdvZ5nwDrsRhF4aIQx3PV4H+YZqTOC6vtFx7zXR16I2ohkHE7RpxB5zIw7hoQKYKM5XDuA5W\
        RHw2Z2cEUU76ZuFlUHiAYU6pBmMQzPd+gNCJf6+AlqWnsK2NEmPpYdbUYQS1OMcal1sgknxKKzdUgStU\
        yepcSbfx3mv2jY6QbRdyNWeCIUXYcD1ZERMjhOBYeaDIg8leIEExivOR7OVJ25OLeJ/Oj2fn+zoF76jC\
        ZrLA7vuxO5Jk9ic5TfhEkqm5ftkl1RSYYBvYDZjUgmyboPiu3O8Vsa9n6iY1zpl6xlPkiXac0Tvv2yxL\
        lsHq1Jr8qOSLfg1vQkIo/1GmDxBjkBQG9wsAtVT/MEY=\
      "
    on:
      repo: aetheric/http-constants
      all_branches: true

  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "\
        YPsMxpn79b3iubeKq52ZRmgnE1eNUEd/f9OfoSX3gMThm1DhTwD+Ok7ySpnHVjpEYCLURvA3Au1tDjAd\
        ad+A12Py+sME2+bQVqNA1Z9Ku3yzks+3BETnOFrcfW/dtlmDA/dLwFp6crswnC3o5ANxmpxaj0ECmJ0p\
        U+642E+KfNLg4aG4DMp5TmOU9jfYgZ4ZmtLHT4bUipq8sQF1Th36JSesVp8B0VImszTojv3u80JRzw7Q\
        NMuHaGHns6jBu8W9qdEYTSLNnwS7tBV+ejUYAHCvEKQumnEFivL/lpeL4XqPZ7Asbu09R+jmph9RbJ5v\
        PfrmDP854Q5fxcVORKT5sBLekRJIEkpUivLDDmfGtFrMhzrHEEnFH9wykYLu0xXnN01TALtuML8LcQt8\
        7WYHoBr0MgMnjd+eENePIjTFjDeO6JNn+JSsEN6xRUwF8TD/YleD4QXqbzIep9har7fLfFkIjpHQcT2p\
        f/aYAbu33XU+kuLaVZ7XdMj0kW5kEysMcpXaHjsjZ+WS3hHi/WvkMaPlI7xadssJsx6U3/j1gh9XGo4m\
        Sb9lMhlvKgdL3YY3zz01z5kjRSfgn/fFYB6UAfHNyNSsQhaqpYYwzuOTLSFKmN9W74gcOpaK1472/3Wz\
        nZiFXdxdVn9iQswsmWi7IsnhdmVcmll9hucAaIz16bU=\
      "
    file:
      - target/dist/consts.js
      - target/dist/consts.min.js
    on:
      repo: aetheric/http-constants
      tags: true
